# frozen_string_literal: true

module DemoApp
  class HomeModel < ApplicationModel
    attribute :title, :string, default: "Charming demo"
    attribute :count, :integer, default: 0

    attr_reader :entries

    def initialize(**attributes)
      super
      @entries = ["Demo app generated by Charming"]
    end

    def increment
      self.count += 1
      log "Incremented to #{count}"
    end

    def decrement
      self.count -= 1
      log "Decremented to #{count}"
    end

    def reset
      self.count = 0
      log "Reset to 0"
    end

    def log(message)
      entries << message
    end
  end
end
